---
functional:
  - Пользователь должен иметь возможность провести пробную игру без входа и регистрации
  - Пользователь должен иметь возможность зарегистрироваться в приложении
  - Пользователь должен иметь возможность войти в приложение под своими учетными данными
  - Пользователь должен иметь возможность входа с помощью github и discord
  - Пользователь должен иметь возможность выйти из под своих учетных данных в приложении
  - Приложение должно определять ранг и рейтинг игрока среди других игроков в течении всего периода существования аккаунта 
  - Пользователь должен иметь возможность сменить свое имя и название клана в приложении
  - Пользователь должен иметь возможность настраивать звуковое сопровождение в игре
  - Пользователь должен иметь возможность создать свою игру в приложении
  - Пользователь должен иметь возможность играть в созданные игры
  - Пользователь должен иметь возможность просматривать список доступных игр
  - Пользователь должен иметь возможность просматривать список турниров
  - Пользователь должен иметь возможность создавать собственные турниры
  - Пользователь должен иметь возможность учавствовать в турнирах
  - Пользователь должен иметь возможность просматривать список всех проведенных в приложении игр 
  - Пользователь должен иметь возможность просматривать рейтинг всех игроков
  - Пользователь должен иметь возможность писать в общий чат всем игрокам 
  - Пользователь должен иметь возможность писать в персональных чатах другим игрокам 
  - Пользователь должен иметь возможность приглашать на игру других пользователей из лобби 
  - Пользователь должен иметь возможность откликаться на приглашения других игроков
  - Пользователь должен иметь возможность видеть игроков онлайн
  - Пользователь должен иметь возможность просматривать свой профиль и статистику о себе
  - Пользователь должен иметь возможность просматривать профили и статистику других игроков 
  - Пользователь должен иметь возможность просматривать список задач используемых в ихрах 
  - Пользователь должен иметь возможность просматривать каждую задачу отдельно 
  - Пользователь должен иметь возможность создавать собственные задачи и редактировать их
  - Пользователь должен иметь возможность создавать собственные пакеты задач и редактировать эти пакеты 
  - Пользователь должен иметь возможность восстановить пароль в случае утраты
non-functional:
  - discription page:
    - Приложение должно иметь стартовую-презентационную страницу 
    - Самое первое действие пользователя на странице должно вызывать всплывающее окно с предложение установить расширение для chrome
    - Стартовая-презентационная страница должна иметь ссылки на страницу регистрации, входа и простой пробной игры
  - header:
    - Приложение должно иметь шапку с логотипом и кнопки sign in и sign up для неавторизованных пользователей 
    - Кнопка sign in должна вести на страницу авторизации 
    - Кнопка sign up должна вести на страницу регистрации
    - Начатие на логотип должно вести на стартовую-презентационную страницу если пользователь не авторизован и на главную страницу если пользователь авторизован 
    - Приложение Должно иметь шапку с логотипом, колличеством игроков онлайн, кнопкой для просмотра приглашений, никнеймом, рангом и аватаркой для авторизованных пользователй
    - Кнопка для просмотра приглашений должна отображаться с подсказкой числа приглашений (если приглашений нет, подсказка не отображается)
    - Кнопка для просмотра приглашений при нажатии раскрывает список приглашений с информацией о том кто пригласил, сложности игры и возможностью принять или отклонить каждое приглашение
    - Нажатие на блок с никнеймом, рангом и аватаркой должно раскрывать вспомогательное меню
    - Вспомогательное меню должно содержать ссылки my profile, settings, users rating, tasks, thurnaments, sourceCode, hexlet, join discord, tg#codebattle, sing out
    - Ссылка my profile должна вести на страницу с информацией об авторизованном пользователе 
    - Ссылка settings должна вести на страницу настроек приложения
    - Ссылка users rating должна вести на страницу с рейтинком игроков 
    - Ссылка tasks должна вести на страницу со списком всех задачь на сайте 
    - Ссылка thurnaments должна вести на страницу просмотра списка турниров с формой для создания товых турниров
    - Ссылка sourceCode ведет на страницу приложения на github
    - Ссылка hexlet ведет на главную страницу сайта hexlet
    - Ссылка join discord ведет на страницу с приглашением присоединиться к дискорд серверу
    - Ссылка tg#codebattle ведет в телеграм чат сообщества хекслет по теме codebattle
    - Ссылка sing out разлогинит пользователя 
  - user page:
    - Страница любого пользователя должна содержать аватарку пользователя, nikname, язык программирования, датау регистрации, достижения, кроме того панель с вкладками statistics и completed games
    - Панель на вкладке statistics должна содержать ранк игрока, рейтинг, информацию о колличестве сыгранных игр, график с частотой использывания языков, график побед и поражений и таблицу активности игрока
    - Панель на вкладке completed games должна состоять из списка проведенных игр в табличной форме со столбцами level, players, date, actions с кнопкой show для показа подробностей игры
    - Панель на вкладке completed games должна содержать информацию о колличестве сыгранных игр
  - settings page: 
    - Страница настроек должна состоять из настроек имени и названия клана, выбора языка программирования, выбора типа и громкости звукового сопровождения, кнопкой save и ссылками для подключения и отключения аккаунтов github и discord
    - Кнопка save должна сохранять внесенные изменения 
    - Пользователь не может отключить аккаунт github или discord если ранее он зарегистрировался с помощью github или discord соответственно
  - users rating page:
    - Страница с рейтингом пользователей должна состоять из панели выбора периода за который отображается рейтинг (за неделю, месяц или за все время), сколько всего пользователей в рейтинге и таблицу рейтинга пользователей 
    - Таблица рейтинга пользователей должна состоять из столбцов №, user, rank, rating, game played, joined, github
    - Столбец github должен содержать ссылку на github пользователя если github пользователя привязан к аккаунту 
    - Таблица рейтинга пользователей должна иметь поиск по имени пользователя, настройки колличества пользователей на одной странице (20, 30, 40, 50) и настройка добавления в список ботов
    - Информация в таблице рейтинга пользователей должна иметь функцию сортировки по убыванию или возрастанию по следующим полям rank, rating, game played, joined
    - При наведении на ник игрока в столбце user должно всплывать окошко с дополнительной информацией об игроке 
    - Окошко с дополнительной информацией об игроке должно содержать аватарку, ник, язык программирования, ранг, рейтинг, колличество выигранных и проигранных игр, колличество сдач и эмблемки с достижениями игрока 
  - tasks page:
    - Страница со списком задач должна состоять из кнопок "create new task", "task packs" и списка задач
    - Список задач должен быть представлен в виде таблицы со столбцами name, level, tags, origin, state, visibility, action
    - Поле action должно содержать кнопку show и вести на страницу с подробностями о задаче 
    - Кнопка "create new task" должна открывать страницу создания новой задачи
    - Кнопка "task packs" должна вести на страницу со списком пакетов задач 
  - creation task page:
    - Страница создания задачи должна иметь подсказки по использованию интерфейса или инструкцию по созданию задачи
  - task packs page:
    - Должна иметь список пакетов задач представленный в табличной форме со столбцами name, state, visibility, task_ids, actions
    - Столбец action должен содержать кнопку show для перехода на страницу конкретного пакета задач
    - Должна быть кнопка create new task pack ведущая на страницу создания пакета задач 
    - Должна быть кнопка tasks ведущая обратно на страницу со списком всех задач на сайте 
  - current task pack page: 
    - Страница пакета задач должна содержать информацию visibility (hidden, public), state, creator_id, таблицу задач со столбцами id, name, level, tags, origin, state, visibility и кнопок edit, delete, back
    - Кнопка edit должна открывать страницу для редактирования текущего пакета задач (такая же как и для создания пакета задач)
    - Кнопка delete должна вызывать всплывающее окно с подтверждением действия, после подтверждения удалять пакет задач и возвращать на страницу списка пакетов задач
    - Кнопка back должна возвращать на страницу со списком пакетов задач
  - create task packs page:
    - Страница создания пакета задач состоит из поля name, выподающего списка visibility (hidden, public), поля task_ids, кнопок save и back 
    - Кнопка save должна сохранять созданный пакет задач и открывать страницу созданного пакета задач
    - Кнопка save сохраняет пакет задач если все поля заполненны корректно
    - В случае неправильного заполнения полей, после назатия на кнопку save должна выводиться подсказка об ошибке 
    - Кнопка back возвращает на страницу со списком пакетов задач
  - tournaments page:
    - Страница турниров должна состоять из списка турниров в табличной форме и формы для создания нового турнира 
    - Таблица со списком турниров должна иметь следующие столбцы name, type, level, state, starts_at, action
    - Столбец action должен содержать кнопку "show" для перехода на страницу конкретного турнира
    - Форма для создания нового турнира должна состоять из полей name, type, description, start at, access type, task strategy, score strategy, task provider, level, event, players limit, default language, match timeout seconds, break duration seconds, чекбоксов use chat и use timer и кнопки create
    - Кнопка create должна создавать новый турнир в случае если форма для создания была заполнена корректно
    - Если форма была заполнена не правильно после нажатия на кнопку create должны появляться подсказки об ошибках
  - tournament page:
    - Страница каждого турнира должна содержать информацию о начале турнира или о том что он уже завершон, чат, информацию о кол-ве игроков, описание турнира
    - Если турнир завершен то должна быть кнопка возвращения к списку турниров
    - Если турнир еще не начался должна быть кнопка join для присоединения к турниру (если есть доступ)
  - registration page:
    - Страница регистрации должна иметь форму с полями nickname, email, password, password confirmation и кнопкой submit
    - Поле nickname должно иметь валидацию длинны (от 3 до 16)
    - Поле email должно иметь валидацию на корректность введенного адреса электронной почты
    - Поле password должно иметь валидацию длинны (от 6 до 16)
    - Поле password confirmation должно иметь проверку на совпадение с полем password
    - Поля nickname, email, password и password confirmation должны иметь подсказку в случае неправильного ввода 
    - Страница регистрации должна иметь кнопки для регистрации с помощью Github и Discord
    - Страница регистрации должна иметь ссылку для перехода на страницу входа
  - login page:
    - Страница входа должна иметь форму с полями email, password и кнопкой submit
    - Поле email должно иметь валидацию на корректность введенного адреса электронной почты
    - Форма входа должен возвращать информацию с текстом ошибки после неудачной попытки входа 
    - Страница входа должна иметь ссылка на востановление пароля 
    - Страница входа должна иметь ссылку на страницу регистрации
    - Страница входа должна иметь кнопки входа с помощью github и discord 
  - password recovery page:
    - Страница восстановления пароля должна иметь форму с полем email и кнопкой submit
    - Поле email должно иметь валидацию на корректность введенного адреса электронной почты
    - Форма восстановления пароля должна возвращать информацию с текстом ошибки после неудачной попытки выполнения восстановления пароля
    - Страница восстановления пароля должна иметь ссылки для перехода на страницу регистрации и входа 
    - На указанный на странице восстановления пароля email должна приходить инструкция по смене пароля 
    - В инструкции по смене пароля должна быть ссылка на форму для указания нового пароля
    - Форма для указания нового пароля должна состоять из поля для ввода пароля и кнопки сохранить
  - home page:
    - На главной странице авторизованного пользователя должны отображаться панели чата, рейтинга игроков, информацией об играх, а так же кнопка "создать игру"
    - Панель чата должна состоять из чата, поля для ввода сообщения с кнопкой отправить, панелью со списком онлайн пользователей и кнопок создания чата и приглашения на игру
    - Панель рейтинга игроков (leaderboard) должна состоя из списка лучших игроков с возможностью фильтрации по времени (за месяц, за неделю, за все время)
    - Панель информации об играх должна состоять из списка доступных для участия и просмотра игр (lobby), списка турниров и списка с историей игр с возможностью переключения между списками
    - Кнопка создать игру должна открывать меню создания игры
    - При наведении на ник игрока в lobby или в leaderboard должно всплывать окошко с дополнительной информацией об игроке 
    - Окошко с дополнительной информацией об игроке должно содержать аватарку, ник, язык программирования, ранг, рейтинг, колличество выигранных и проигранных игр, колличество сдач и эмблемки с достижениями игрока 
  - game creation: 
    - Меню создания игры должно включать в себя настройки сложности, выбор типа игры, продолжительности игры, задачи (опционально) и кнопкой "создать игру"
    - В случае создания игры с типом "with other user" или "with a friend" должно закрыться меню создания игры и открыться главная страница где пользователь будет ждать другого игрока
    - Когда другой игрок выберет присоединиться к игре с типом "with other user" или "with a friend", созданной пользователем, откроется страница для решения задачи
    - В случае создания игры с типом "bot" сразу откроется страница для решения задачи
  - game page: 
    - Страница для решения задаци состоит из панели с условием задачи, результатом тестов и таймером, панели чата, панели для редактирования своего кода и панели отображающей код соперника
    - Панели с условием задачи, результатом тестов и таймером должна иметь функционал переключения между окном задачи и окном с результатом тестов 
    - Окно с условием задачи должно иметь кнопку перекллючения языка между английским и русским, кнопку отображения задачи в отдельном окне и кнопку вызова подсказки по использованию интерфейса
    - Панель чата должна состоять из чата, поля ввода сообщения с кнопкой отправить, и списком онлайн игроков в данной игре, а так же кнопкой перехода на главную
    - Панель для редактирования кода должна состоять из пространства с кодом и верхней панели с выбором языка программирования, стилем редактора, кнопками сдаться, очистить редактор кода и проверкой решения
    - Панель отображающая код соперника должна отображать язык программирования соперника и пространство с его кодом
  - footer:
    - Футер должен состоять из ссылки на сайт Хекслет и ссылки на текущий комит на github
  - other:
    - Информация о проведенных играх должна храниться на сервере
    - Информация о пользователях, их взаимодействии и настройках должна храниться на сервере 
    - Сайт должен быть безопасным и защищать данные пользователя
    - Сайт должен быть кросплатформенным 
    - Сайт должен быть кросбраузерным
    - Сайт должен быть адаптивным 
    - Сайт должен быть способен обработать 1000 одновременных пользователей
    - Сайт должен быть способен масштабироваться для обработки увеличившегося числа пользователей без потери производительности
    - Сайт должен быть доступным для пользователей с ограниченными возможностями
    - Сайт должен быть отказоустойчив и обеспечивать возможность восстановления после сбоев без потери данных
    - Сайт должен обеспечивать быструю загрузку страницы и выполнения операций
    - Сайт должен быть легко расширяем для добавления новых функций и изменения существующих 
    - Сайт должен автоматически собирать и анонимно хранить статистическую информацию об использовании приложения
implicit:
  - Весь контент любой стриницы должен быть выравнен по центру (по горизонтали) 
  - Информация о онлайн игроках должна обновляться в "реальном времени"
  - Информация о играх в lobby должна обновляться в "реальном времени"
  - В чатах сообщение должно состоять из имени отправителя, времени отправления и сообщения
  - Переключения между страницами должны происходить без перезагрузки страницы 
  - Всплывающие окна должны закрывать на крестик в верхнем правом углу и на нажатие по области экрана за пределами всплывающего окна 
  